require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/HashAlignment:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false
